name: Driver API_VERSION checks
on:
  push:
    branches: [main]

jobs:
  loving-bash:
    runs-on: ubuntu-latest
    steps:
    - name: heredoc bash script
      run: |
        cat > ~/sign <<EOF
        #!/bin/bash
        echo "hello hello"
        echo "hello2"
        EOF
        chmod +x ~/sign
        
        ~/sign
