name: Find out things about my release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'   # final release
      - '[0-9]+.[0-9]+.[0-9]+-*' # prerelease/RC
    
jobs:
  get-release-info:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        uses: rez0n/actions-github-release@v2.0
        id: latest_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          type: "stable"

      - name: Print outputs
        shell: python
        run: |
          print("id: ${{ steps.latest_release.outputs.release }}")


