name: Find out things about my release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'   # final release
      - '[0-9]+.[0-9]+.[0-9]+-*' # prerelease/RC
    
jobs:
  release-settings:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release
        uses: rez0n/actions-github-release@v2.0
        id: latest_release
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          type: "stable"

      - name: Get settings for this release
        id: get_settings
        shell: python
        run: |
          import os
          prerelease = '-' in '${{ github.ref_name }}'

          # Safeguard: you need to both set "latest" in GH and not have suffixes to overwrite latest
          is_latest = '${{ steps.latest_release.outputs.release }}' == '${{ github.ref_name }}' and not prerelease

          bucket_suffix = '' if is_latest else '-dev'

          with open(os.environ['GITHUB_OUTPUT'], 'a') as ofp:
            print(f'is_latest={is_latest}'.lower(), file=ofp)
            print(f'bucket_suffix={bucket_suffix}', file=ofp)

    outputs:
      is_latest: ${{ steps.get_settings.outputs.is_latest }} 
      bucket_suffix: ${{ steps.get_settings.outputs.bucket_suffix }}


  test-output:
    runs-on: ubuntu-latest
    needs: [release-settings]

    steps:
      - name: Print outputs
        run: |
          echo "is_latest = ${{ needs.release-settings.outputs.is_latest }}"
          echo "bucket_suffix = ${{ needs.release-settings.outputs.bucket_suffix }}"

      - name: Run if latest
        if: ${{ needs.release-settings.outputs.is_latest == 'true' }}
        run: echo "this is latest!"

