name: Find out things about my release
on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'   # final release
      - '[0-9]+.[0-9]+.[0-9]+-*' # prerelease/RC
    
jobs:
  get-release-info:
    runs-on: ubuntu-latest
    steps:
      - id: latest_release
        name: Get latest release
        uses: pozetroninc/github-action-get-latest-release@d1dafdb6e338bdab109e6afce581a01858680dfb
        with:
          repository: ${{ github.repository }}
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print outputs
        shell: python
        run: |
          print("id: ${{ steps.latest_release.outputs.release }}")


