name: Create and publish container images

on:
  workflow_call:
    inputs:
      is_latest:
        description: Update the latest tag with the new image
        required: false
        type: boolean
        default: false
      version:
        description: The version
        required: true
        type: string

jobs:
  build-images:
    permissions:
      id-token: write
      contents: read
      packages: write

    runs-on: ubuntu-latest
    steps:
      - name: "test 1"
        run: echo "this is a test"
      
      - name: "test only if latest"
        if: ${{ inputs.is_latest }}
        run: echo "this needs to run only for latest"

      - name: Build image x86_64
        uses: docker/build-push-action@v3
        with:
          build-args: |
            VERSION=${{ inputs.version }}
          tags: |
            lucagsd/test-gha-pr:x86_64-${{ inputs.version }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Build image arm64
        uses: docker/build-push-action@v3
        with:
          platforms: linux/arm64
          build-args: |
            VERSION=${{ inputs.version }}
          tags: |
            lucagsd/test-gha-pr:aarch64-${{ inputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_SECRET }}

      - name: Setup Crane
        uses: imjasonh/setup-crane@v0.3
        with:
          version: v0.15.1

      - name: Setup Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: v2.0.2

      - name: Push images to Docker Hub
        run: |
          docker push lucagsd/test-gha-pr:aarch64-${{ inputs.version }}
          docker push lucagsd/test-gha-pr:x86_64-${{ inputs.version }}

      - name: Create and push manifest
        uses: Noelware/docker-manifest-action@0.3.1
        with:
          inputs: lucagsd/test-gha-pr:${{ inputs.version }}
          images: lucagsd/test-gha-pr:aarch64-${{ inputs.version }},lucagsd/test-gha-pr:x86_64-${{ inputs.version }}
          push: true

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: lucaguerra
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get digest
        id: get_digest
        run: |
          echo "image_digest=$(crane digest lucagsd/test-gha-pr:${{ inputs.version }})" >> $GITHUB_OUTPUT

      - name: Push to GHCR
        run: |
          crane copy lucagsd/test-gha-pr:${{ inputs.version }} ghcr.io/lucaguerra/test-gha-pr:${{ inputs.version }}

      - name: Tag latest
        if: inputs.is_latest
        run: |
          crane tag lucagsd/test-gha-pr:${{ inputs.version }} latest
          crane tag ghcr.io/lucaguerra/test-gha-pr:${{ inputs.version }} latest

      # verify with
      # cosign verify docker.io/lucagsd/test-gha-pr:latest --certificate-oidc-issuer=https://token.actions.githubusercontent.com --certificate-identity=https://github.com/LucaGuerra/test-gha-pr/.github/workflows/reusable_publish_image.yaml@refs/heads/main
      - name: Sign image with cosign
        env:
          COSIGN_EXPERIMENTAL: "true"
          COSIGN_YES: "true"
        run: |
          cosign sign lucagsd/test-gha-pr@${{ steps.get_digest.outputs.image_digest }}
          cosign sign ghcr.io/lucaguerra/test-gha-pr@${{ steps.get_digest.outputs.image_digest }}
